### ISSUE TITLE
incorrect link about storageless upgradeable beacon proxy

### ISSUE THREAD

**Issue by wiasliaw** [YAcademy-Residents/Proxies-website#16]
https://github.com/YAcademy-Residents/Proxies-website/blob/510d791a8d27d2c7d1bfe2e0057f81ad7fedb77c/pages/Proxies-Table.md?plain=1#L18

The link in the summary should be [this](https://forum.openzeppelin.com/t/a-more-gas-efficient-upgradeable-proxy-by-not-using-storage/4111), not the UUPS.

**Comment by engn33r** [comment]
Fixed by #17
